### ISSUE TITLE
rpc_f5_config.sh is not generating a VIP for port 8181 (pip repo)

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-extras#91] opened 2015-04-30 18:05 UTC
rpc_f5_config.sh is not generating a VIP for port 8181 for the repo container. That needs to be addressed asap.

**Comment by miguelgrinberg** [comment] 2015-04-30 18:31
I think this is covered by the changes in #89, we have port 8181 there.

**Comment by b3rnard0** [comment] 2015-05-05 15:37
Calling this a duplicate of #89 , which is currently being reviewed.

**Closed by b3rnard0** 2015-05-05 15:37 UTC
Labels: status-duplicate, type-bug
